name: pizza_rush
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  animated_custom_dropdown: 3.1.1
  flutter:
    sdk: flutter
  flutter_stripe: ^10.1.1
  http: ^1.2.0
  provider: ^6.1.2
  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  sqflite: ^2.4.0
  sqflite_common_ffi: ^2.3.4  # For FFI support (only for desktop platforms)
  path: ^1.9.0
  google_maps_flutter: ^2.12.1
  flutter_dotenv: ^5.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
     - lib/assets/images/

